export const navItems = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
  },
  {
    id: 'users',
    label: 'Users',
    icon: 'users',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    icon: 'analytics',
  },
  {
    id: 'revenue',
    label: 'Revenue',
    icon: 'revenue',
  },
];

export const users = [
  {
    id: 1,
    name: 'Ahmad Saleh',
    email: 'ahmad@example.com',
    storeName: 'Ahmad Store',
    businessType: 'Clothing',
    plan: 'Pro',
    imagesRemaining: 120,
    status: 'Active',
    joinedAt: '2026-05-01',
  },
  {
    id: 2,
    name: 'Sara Ali',
    email: 'sara@example.com',
    storeName: 'Sara Beauty',
    businessType: 'Cosmetics',
    plan: 'Free',
    imagesRemaining: 8,
    status: 'Active',
    joinedAt: '2026-05-03',
  },
  {
    id: 3,
    name: 'Omar Khaled',
    email: 'omar@example.com',
    storeName: 'Omar Tech',
    businessType: 'Electronics',
    plan: 'Premium',
    imagesRemaining: 300,
    status: 'Active',
    joinedAt: '2026-05-05',
  },
  {
    id: 4,
    name: 'Lina Nasser',
    email: 'lina@example.com',
    storeName: 'Lina Home',
    businessType: 'Furniture',
    plan: 'Pro',
    imagesRemaining: 0,
    status: 'Inactive',
    joinedAt: '2026-05-07',
  },
  {
    id: 5,
    name: 'Yazan Hamed',
    email: 'yazan@example.com',
    storeName: 'Yazan Market',
    businessType: 'Grocery',
    plan: 'Free',
    imagesRemaining: 15,
    status: 'Active',
    joinedAt: '2026-05-09',
  },
];